theme: jekyll-theme-merlot
title: Welcome to Jason Kuphaldt's homepage!
description: Look around and see what I am up to with my projects.

## Some of my interests

My name is Jason Kuphaldt. I am a Computer Science major at Boise State University. I am also minoring in Japanses Studies.
はじめまして！

In my free time, I like to play video games, watch movies, listen to music, and watch anime. Listed below are some of my favorites of each!

- Favorite game: [Kingdom Hearts II](https://en.wikipedia.org/wiki/Kingdom_Hearts_II)
- Favorite movie: [Whiplash](https://en.wikipedia.org/wiki/Whiplash_(2014_film))
- Favorite album: [Saturation - Brockhampton](https://en.wikipedia.org/wiki/Saturation_(Brockhampton_album))
- Favorite anime: [March comes in like a lion](https://en.wikipedia.org/wiki/March_Comes_in_Like_a_Lion)

I also enjoy running, going to the gym, and skiing!

